List<String> information = [
  'Los azúcares libres se diferencian de los azúcares intrínsecos que se encuentran en las frutas y las verduras enteras frescas. Como no hay pruebas de que el consumo de azúcares intrínsecos tenga efectos adversos para la salud, las recomendaciones de la directriz no se aplican al consumo de los azúcares intrínsecos presentes en las frutas y las verduras enteras frescas. La recomendación se apoya además en datos que evidencian que un consumo de azúcares libres superior al 10% de la ingesta calórica total produce tasas más elevadas de caries dental que un consumo inferior al 10% de la ingesta calórica total. \n'+
  'Fuente: https://www.who.int/nutrition/publications/guidelines/sugar_intake_information_note_es.pdf',
  'Las grasas no saturadas (presentes en pescados, aguacates, frutos secos y en los aceites de girasol, soja, canola y oliva) son preferibles a las grasas saturadas (presentes en la carne grasa, la mantequilla, el aceite de palma y de coco, la nata, el queso, la mantequilla clarificada y la manteca de cerdo), y las grasas trans de todos los tipos, en particular las producidas industrialmente (presentes en pizzas congeladas, tartas, galletas, pasteles, obleas, aceites de cocina y pastas untables), y grasas trans de rumiantes (presentes en la carne y los productos lácteos de rumiantes tales como vacas, ovejas, cabras y camellos). Se sugirió reducir la ingesta de grasas saturadas a menos del 10% de la ingesta total de calorías, y la de grasas trans a menos del 1% (5). En particular, las grasas trans producidas industrialmente no forman parte de una dieta saludable y se deberían evitar (4,6). \n'+
  'Fuente:https://www.who.int/es/news-room/fact-sheets/detail/healthy-diet',
  'Un mayor consumo de sodio se asocia con un riesgo más alto de accidentes cerebrovasculares (ACV) nuevos, ACV mortales ni cardiopatías coronarias mortales. No se observa ninguna relación entre el consumo de sodio y la mortalidad por cualquier causa, la incidencia de enfermedades cardiovasculares o cardiopatía coronaria no mortales. No obstante, la marcada relación positiva entre la tensión arterial y esas enfermedades constituye una prueba indirecta de que la reducción del consumo de sodio puede mitigar esos problemas gracias a su efecto beneficioso sobre la tensión. La OMS recomienda rebajar el consumo de sodio a fin de reducir la tensión arterial y el riesgo de enfermedades cardiovasculares, ACV y cardiopatía coronaria entre los adultos (recomendación firme 1 ). La OMS recomienda reducir la ingesta de sodio por debajo de los 2 g (5 g de sal) al día en el caso de los adultos (recomendación firme). \n'+
  'Fuente:https://apps.who.int/iris/bitstream/handle/10665/85224/WHO_NMH_NHD_13.2_spa.pdf;jsessionid=060ED3374CDE5F1D794E86BF7F570CB7?sequence=1',
  'Healthcam, nace con el propósito de ayudar a las personas a identificar lo que están consumiendo con los alimentos. Es una aplicación móvil que servirá como proyecto final a estudiantes de ingeniería electrónica. Se aplican conocimiento en procesamiento digital de imagen con la ayuda de librerías de machine learning.'

];